spring.application.name=netequip
spring.datasource.url=jdbc:postgresql://localhost:5432/netequip
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:MySecretKeyForHmac256MustBe32CharsLong!}